-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRskXJuJHvzZZNHvF
fzG6h63xzd6GnYlaZoF7inXSVjigCgYIKoZIzj0DAQehRANCAARsgfnGZHXKOJmV
a8GXjilV6P6Otnt6ACuB5eAMoVP4XMnLt8WmCIZlZcbRPkmX/x8Dy0ea0uv81sB9
LeDic0nA
-----END PRIVATE KEY-----